#!/user/bin/python3
# SPDX-FileCopyrightText: 2023 Yusuke Fujikawa
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    exept:
        ans += float(line)

print(ans)
