#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Yusuke Fujikawa
# SPDX-License-Identifier: BSD-3-Clause

import sys 

ans = 0
q = 0
for line in sys.stdin:
    try:
        ans += int(line)
        q -= int(line)
    except:
        ans += float(line)
        q -= float(line)

print(ans,q)
